// Code generated by gorm-gen. DO NOT EDIT.
package query

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

type AnonymousUserDO struct {
	ID        int64          `gorm:"primaryKey;column:id;type:bigint;not null" json:"id"`
	UUID      string         `gorm:"column:uuid;type:varchar(36);not null;uniqueIndex" json:"uuid"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index" json:"deleted_at"`
}

func (AnonymousUserDO) TableName() string {
	return "anonymous_users"
}

type anonymousUserRepo struct {
	db *gorm.DB
}

func NewAnonymousUserRepo(db *gorm.DB) *anonymousUserRepo {
	return &anonymousUserRepo{db: db}
}

func (r *anonymousUserRepo) Create(ctx context.Context, user *AnonymousUserDO) error {
	result := r.db.WithContext(ctx).Create(user)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *anonymousUserRepo) GetByID(ctx context.Context, id int64) (*AnonymousUserDO, error) {
	var user AnonymousUserDO
	result := r.db.WithContext(ctx).First(&user, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrAnonymousUserNotFound
		}
		return nil, result.Error
	}
	return &user, nil
}

func (r *anonymousUserRepo) GetByUUID(ctx context.Context, uuid string) (*AnonymousUserDO, error) {
	var user AnonymousUserDO
	result := r.db.WithContext(ctx).Where("uuid = ?", uuid).First(&user)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrAnonymousUserNotFound
		}
		return nil, result.Error
	}
	return &user, nil
}

func (r *anonymousUserRepo) Update(ctx context.Context, user *AnonymousUserDO) error {
	result := r.db.WithContext(ctx).Save(user)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *anonymousUserRepo) Delete(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).Delete(&AnonymousUserDO{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrAnonymousUserNotFound
	}
	return nil
}

func (r *anonymousUserRepo) List(ctx context.Context, offset, limit int) ([]*AnonymousUserDO, error) {
	var users []*AnonymousUserDO
	result := r.db.WithContext(ctx).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&users)
	if result.Error != nil {
		return nil, result.Error
	}
	return users, nil
}

func (r *anonymousUserRepo) Count(ctx context.Context) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).Model(&AnonymousUserDO{}).Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

var (
	ErrAnonymousUserNotFound = errors.New("匿名用户不存在")
)

func (r *anonymousUserRepo) WithContext(ctx context.Context) *gorm.DB {
	return r.db.WithContext(ctx)
}

func (r *anonymousUserRepo) Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error {
	return r.db.Transaction(func(tx *gorm.DB) error {
		return fn(tx)
	})
}

type AnonymousUserRepo interface {
	Create(ctx context.Context, user *AnonymousUserDO) error
	GetByID(ctx context.Context, id int64) (*AnonymousUserDO, error)
	GetByUUID(ctx context.Context, uuid string) (*AnonymousUserDO, error)
	Update(ctx context.Context, user *AnonymousUserDO) error
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, offset, limit int) ([]*AnonymousUserDO, error)
	Count(ctx context.Context) (int64, error)
	WithContext(ctx context.Context) *gorm.DB
	Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error
}
