// Code generated by gorm-gen. DO NOT EDIT.
package query

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

var ErrAttachmentNotFound = errors.New("附件不存在")

type AttachmentDO struct {
	ID          int64          `gorm:"primaryKey;column:id;type:bigint;not null" json:"id"`
	UserID      int64          `gorm:"column:user_id;type:bigint;not null;index" json:"user_id"`
	Filename    string         `gorm:"column:filename;type:varchar(255);not null" json:"filename"`
	Size        int64          `gorm:"column:size;type:bigint;not null" json:"size"`
	ContentType string         `gorm:"column:content_type;type:varchar(100);not null" json:"content_type"`
	MinioKey    string         `gorm:"column:minio_key;type:varchar(500);not null;uniqueIndex" json:"minio_key"`
	MinioURL    string         `gorm:"column:minio_url;type:varchar(500);not null" json:"minio_url"`
	FileType    string         `gorm:"column:file_type;type:varchar(20);not null;default:'file'" json:"file_type"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index" json:"deleted_at"`
}

func (AttachmentDO) TableName() string {
	return "attachments"
}

type AttachmentRepo struct {
	db *gorm.DB
}

func NewAttachmentRepo(db *gorm.DB) *AttachmentRepo {
	return &AttachmentRepo{db: db}
}

func (r *AttachmentRepo) Create(ctx context.Context, attachment *AttachmentDO) error {
	result := r.db.WithContext(ctx).Create(attachment)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *AttachmentRepo) GetByID(ctx context.Context, id int64) (*AttachmentDO, error) {
	var attachment AttachmentDO
	result := r.db.WithContext(ctx).First(&attachment, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrAttachmentNotFound
		}
		return nil, result.Error
	}
	return &attachment, nil
}

func (r *AttachmentRepo) GetByMinioKey(ctx context.Context, minioKey string) (*AttachmentDO, error) {
	var attachment AttachmentDO
	result := r.db.WithContext(ctx).Where("minio_key = ?", minioKey).First(&attachment)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrAttachmentNotFound
		}
		return nil, result.Error
	}
	return &attachment, nil
}

func (r *AttachmentRepo) Update(ctx context.Context, attachment *AttachmentDO) error {
	result := r.db.WithContext(ctx).Save(attachment)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *AttachmentRepo) Delete(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).Delete(&AttachmentDO{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrAttachmentNotFound
	}
	return nil
}

func (r *AttachmentRepo) ListByUserID(ctx context.Context, userID int64, offset, limit int) ([]*AttachmentDO, error) {
	var attachments []*AttachmentDO
	result := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&attachments)
	if result.Error != nil {
		return nil, result.Error
	}
	return attachments, nil
}

func (r *AttachmentRepo) CountByUserID(ctx context.Context, userID int64) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).Model(&AttachmentDO{}).Where("user_id = ?", userID).Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}
