// Code generated by gorm-gen. DO NOT EDIT.
package query

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

var NamingStrategy = schema.NamingStrategy{}

type CategoryDO struct {
	ID          int64          `gorm:"primaryKey;column:id;type:bigint;not null" json:"id"`
	Name        string         `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Description string         `gorm:"column:description;type:text" json:"description"`
	ParentID    *int64         `gorm:"column:parent_id;type:bigint" json:"parent_id"`
	Position    int            `gorm:"column:position;type:integer;default:0" json:"position"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index" json:"deleted_at"`
}

func (CategoryDO) TableName() string {
	return "ac_categories"
}

type categoryRepo struct {
	db *gorm.DB
}

func NewCategoryRepo(db *gorm.DB) *categoryRepo {
	return &categoryRepo{db: db}
}

func (r *categoryRepo) Create(ctx context.Context, category *CategoryDO) error {
	result := r.db.WithContext(ctx).Create(category)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *categoryRepo) GetByID(ctx context.Context, id int64) (*CategoryDO, error) {
	var category CategoryDO
	result := r.db.WithContext(ctx).First(&category, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrCategoryNotFound
		}
		return nil, result.Error
	}
	return &category, nil
}

func (r *categoryRepo) Update(ctx context.Context, category *CategoryDO) error {
	result := r.db.WithContext(ctx).Save(category)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *categoryRepo) Delete(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).Delete(&CategoryDO{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrCategoryNotFound
	}
	return nil
}

func (r *categoryRepo) List(ctx context.Context, offset, limit int) ([]*CategoryDO, error) {
	var categories []*CategoryDO
	result := r.db.WithContext(ctx).
		Order("position ASC, created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&categories)
	if result.Error != nil {
		return nil, result.Error
	}
	return categories, nil
}

func (r *categoryRepo) GetByParentID(ctx context.Context, parentID *int64) ([]*CategoryDO, error) {
	var categories []*CategoryDO
	query := r.db.WithContext(ctx).Order("position ASC, created_at DESC")
	if parentID == nil {
		query = query.Where("parent_id IS NULL")
	} else {
		query = query.Where("parent_id = ?", *parentID)
	}
	result := query.Find(&categories)
	if result.Error != nil {
		return nil, result.Error
	}
	return categories, nil
}

func (r *categoryRepo) Count(ctx context.Context) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).Model(&CategoryDO{}).Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

var (
	ErrCategoryNotFound = errors.New("分类不存在")
	ErrInvalidInput     = errors.New("无效的输入参数")
)

func (r *categoryRepo) WithContext(ctx context.Context) *gorm.DB {
	return r.db.WithContext(ctx)
}

func (r *categoryRepo) Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error {
	return r.db.Transaction(func(tx *gorm.DB) error {
		return fn(tx)
	})
}

type CategoryRepo interface {
	Create(ctx context.Context, category *CategoryDO) error
	GetByID(ctx context.Context, id int64) (*CategoryDO, error)
	Update(ctx context.Context, category *CategoryDO) error
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, offset, limit int) ([]*CategoryDO, error)
	GetByParentID(ctx context.Context, parentID *int64) ([]*CategoryDO, error)
	Count(ctx context.Context) (int64, error)
	WithContext(ctx context.Context) *gorm.DB
	Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error
}
