// Code generated by gorm-gen. DO NOT EDIT.
package query

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

type CommentDO struct {
	ID         int64          `gorm:"primaryKey;column:id;type:bigint;not null" json:"id"`
	PostID     int64          `gorm:"column:post_id;type:bigint;not null;index" json:"post_id"`
	UserID     *int64         `gorm:"column:user_id;type:bigint" json:"user_id"`
	Content    string         `gorm:"column:content;type:text;not null" json:"content"`
	ParentID   *int64         `gorm:"column:parent_id;type:bigint;index" json:"parent_id"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index" json:"deleted_at"`
}

func (CommentDO) TableName() string {
	return "comments"
}

type commentRepo struct {
	db *gorm.DB
}

func NewCommentRepo(db *gorm.DB) *commentRepo {
	return &commentRepo{db: db}
}

func (r *commentRepo) Create(ctx context.Context, comment *CommentDO) error {
	result := r.db.WithContext(ctx).Create(comment)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *commentRepo) GetByID(ctx context.Context, id int64) (*CommentDO, error) {
	var comment CommentDO
	result := r.db.WithContext(ctx).First(&comment, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrCommentNotFound
		}
		return nil, result.Error
	}
	return &comment, nil
}

func (r *commentRepo) Update(ctx context.Context, comment *CommentDO) error {
	result := r.db.WithContext(ctx).Save(comment)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *commentRepo) Delete(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).Delete(&CommentDO{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrCommentNotFound
	}
	return nil
}

func (r *commentRepo) ListByPostID(ctx context.Context, postID int64, offset, limit int) ([]*CommentDO, error) {
	var comments []*CommentDO
	result := r.db.WithContext(ctx).
		Where("post_id = ?", postID).
		Where("parent_id IS NULL").
		Order("created_at ASC").
		Offset(offset).
		Limit(limit).
		Find(&comments)
	if result.Error != nil {
		return nil, result.Error
	}
	return comments, nil
}

func (r *commentRepo) ListByParentID(ctx context.Context, parentID int64, offset, limit int) ([]*CommentDO, error) {
	var comments []*CommentDO
	result := r.db.WithContext(ctx).
		Where("parent_id = ?", parentID).
		Order("created_at ASC").
		Offset(offset).
		Limit(limit).
		Find(&comments)
	if result.Error != nil {
		return nil, result.Error
	}
	return comments, nil
}

func (r *commentRepo) CountByPostID(ctx context.Context, postID int64) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).
		Model(&CommentDO{}).
		Where("post_id = ?", postID).
		Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

func (r *commentRepo) CountByParentID(ctx context.Context, parentID int64) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).
		Model(&CommentDO{}).
		Where("parent_id = ?", parentID).
		Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

var (
	ErrCommentNotFound = errors.New("评论不存在")
)

func (r *commentRepo) WithContext(ctx context.Context) *gorm.DB {
	return r.db.WithContext(ctx)
}

func (r *commentRepo) Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error {
	return r.db.Transaction(func(tx *gorm.DB) error {
		return fn(tx)
	})
}

type CommentRepo interface {
	Create(ctx context.Context, comment *CommentDO) error
	GetByID(ctx context.Context, id int64) (*CommentDO, error)
	Update(ctx context.Context, comment *CommentDO) error
	Delete(ctx context.Context, id int64) error
	ListByPostID(ctx context.Context, postID int64, offset, limit int) ([]*CommentDO, error)
	ListByParentID(ctx context.Context, parentID int64, offset, limit int) ([]*CommentDO, error)
	CountByPostID(ctx context.Context, postID int64) (int64, error)
	CountByParentID(ctx context.Context, parentID int64) (int64, error)
	WithContext(ctx context.Context) *gorm.DB
	Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error
}
