// Code generated by gorm-gen. DO NOT EDIT.
package query

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

type PostDO struct {
	ID          int64          `gorm:"primaryKey;column:id;type:bigint;not null" json:"id"`
	Title       string         `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Content     string         `gorm:"column:content;type:text;not null" json:"content"`
	AuthorID    *int64         `gorm:"column:author_id;type:bigint" json:"author_id"`
	CategoryID  *int64         `gorm:"column:category_id;type:bigint;index" json:"category_id"`
	ViewCount   int            `gorm:"column:view_count;type:integer;default:0" json:"view_count"`
	LikeCount   int            `gorm:"column:like_count;type:integer;default:0" json:"like_count"`
	Status      int            `gorm:"column:status;type:integer;default:1" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	PublishedAt *time.Time     `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index" json:"deleted_at"`
}

func (PostDO) TableName() string {
	return "posts"
}

type postRepo struct {
	db *gorm.DB
}

func NewPostRepo(db *gorm.DB) *postRepo {
	return &postRepo{db: db}
}

func (r *postRepo) Create(ctx context.Context, post *PostDO) error {
	result := r.db.WithContext(ctx).Create(post)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *postRepo) GetByID(ctx context.Context, id int64) (*PostDO, error) {
	var post PostDO
	result := r.db.WithContext(ctx).First(&post, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrPostNotFound
		}
		return nil, result.Error
	}
	return &post, nil
}

func (r *postRepo) Update(ctx context.Context, post *PostDO) error {
	result := r.db.WithContext(ctx).Save(post)
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *postRepo) Delete(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).Delete(&PostDO{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return ErrPostNotFound
	}
	return nil
}

func (r *postRepo) List(ctx context.Context, offset, limit int) ([]*PostDO, error) {
	var posts []*PostDO
	result := r.db.WithContext(ctx).
		Where("status = ?", 1).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&posts)
	if result.Error != nil {
		return nil, result.Error
	}
	return posts, nil
}

func (r *postRepo) ListByCategory(ctx context.Context, categoryID int64, offset, limit int) ([]*PostDO, error) {
	var posts []*PostDO
	result := r.db.WithContext(ctx).
		Where("category_id = ?", categoryID).
		Where("status = ?", 1).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&posts)
	if result.Error != nil {
		return nil, result.Error
	}
	return posts, nil
}

func (r *postRepo) ListByAuthor(ctx context.Context, authorID int64, offset, limit int) ([]*PostDO, error) {
	var posts []*PostDO
	result := r.db.WithContext(ctx).
		Where("author_id = ?", authorID).
		Order("created_at DESC").
		Offset(offset).
		Limit(limit).
		Find(&posts)
	if result.Error != nil {
		return nil, result.Error
	}
	return posts, nil
}

func (r *postRepo) IncrementViewCount(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).
		Model(&PostDO{}).
		Where("id = ?", id).
		Update("view_count", gorm.Expr("view_count + ?", 1))
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *postRepo) IncrementLikeCount(ctx context.Context, id int64) error {
	result := r.db.WithContext(ctx).
		Model(&PostDO{}).
		Where("id = ?", id).
		Update("like_count", gorm.Expr("like_count + ?", 1))
	if result.Error != nil {
		return result.Error
	}
	return nil
}

func (r *postRepo) Count(ctx context.Context) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).
		Model(&PostDO{}).
		Where("status = ?", 1).
		Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

func (r *postRepo) CountByCategory(ctx context.Context, categoryID int64) (int64, error) {
	var count int64
	result := r.db.WithContext(ctx).
		Model(&PostDO{}).
		Where("category_id = ?", categoryID).
		Where("status = ?", 1).
		Count(&count)
	if result.Error != nil {
		return 0, result.Error
	}
	return count, nil
}

var (
	ErrPostNotFound = errors.New("文章不存在")
)

func (r *postRepo) WithContext(ctx context.Context) *gorm.DB {
	return r.db.WithContext(ctx)
}

func (r *postRepo) Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error {
	return r.db.Transaction(func(tx *gorm.DB) error {
		return fn(tx)
	})
}

type PostRepo interface {
	Create(ctx context.Context, post *PostDO) error
	GetByID(ctx context.Context, id int64) (*PostDO, error)
	Update(ctx context.Context, post *PostDO) error
	Delete(ctx context.Context, id int64) error
	List(ctx context.Context, offset, limit int) ([]*PostDO, error)
	ListByCategory(ctx context.Context, categoryID int64, offset, limit int) ([]*PostDO, error)
	ListByAuthor(ctx context.Context, authorID int64, offset, limit int) ([]*PostDO, error)
	IncrementViewCount(ctx context.Context, id int64) error
	IncrementLikeCount(ctx context.Context, id int64) error
	Count(ctx context.Context) (int64, error)
	CountByCategory(ctx context.Context, categoryID int64) (int64, error)
	WithContext(ctx context.Context) *gorm.DB
	Transaction(ctx context.Context, fn func(tx *gorm.DB) error) error
}
